---
- name: install java
  hosts: all
  remote_user: vagrant
  sudo: yes

  tasks:
  - name: Update
    apt: update_cache=yes

  - name: Move files
    command: "cp /tmp/shared/java.tar.gz /home/vagrant"

  - name: Unpack tar file
    command: "tar zxvf java.tar.gz"

  - name: Install java
    command: "update-alternatives --install /usr/bin/java java /home/vagrant/jdk1.8.0_45/bin/java 100"
